In [3]:
import numpy as np

Basic Array

In [7]:
arr =np.array([1,2,4])
arr

array([1, 2, 4])

In [11]:
a = [1,2.5,True,"hello"]
a

[1, 2.5, True, 'hello']

In [12]:
np.array(a)

array(['1', '2.5', 'True', 'hello'], dtype='<U32')

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr =np.arange(1,101,5)
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [23]:
a = np.ones((6,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
arr = np.linspace(1,10,12)
arr

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

Random genration 

In [29]:
np.random.rand(5)

array([0.49121448, 0.47476065, 0.34753333, 0.86227633, 0.33410643])

In [30]:
np.random.randint(10)

3

In [32]:
np.random.randint(10,15,5)

array([12, 11, 10, 11, 10])

In [33]:
arr.size

12

Array Methods


In [36]:
a = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a.min()

1

In [38]:
a.max()

9

In [42]:
a.sum(axis=1)

array([ 6, 15, 24])

In [43]:
a.mean()

5.0

In [44]:
a.std()

2.581988897471611

Reshaping and Resizing

In [45]:
arr = np.arange(1,21)

In [47]:
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Indexing and Slicing 

In [48]:
arr = np.arange(1,21)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
arr[5]

6

In [62]:
arr_slice = arr[::-1]
arr_slice

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [75]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [76]:
arr[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [79]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20]])

In [81]:
a = np.arange(1,11)
bool = a%2==0

In [82]:
a = a[bool]
a

array([ 2,  4,  6,  8, 10])

Array Opration

In [86]:
a = np.arange(1,6)
b = np.arange(6,11)
a

array([1, 2, 3, 4, 5])

In [85]:
b

array([ 6,  7,  8,  9, 10])

In [88]:
a-b

array([-5, -5, -5, -5, -5])

In [89]:
a*b

array([ 6, 14, 24, 36, 50])

In [90]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [91]:
a//b

array([0, 0, 0, 0, 0])

In [92]:
b//a

array([6, 3, 2, 2, 2])

In [93]:
a**b

array([      1,     128,    6561,  262144, 9765625])

In [94]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [95]:
b

array([[5, 6],
       [7, 8]])

In [96]:
a+b

array([[ 6,  8],
       [10, 12]])

In [97]:
a-b

array([[-4, -4],
       [-4, -4]])

In [98]:
a*b

array([[ 5, 12],
       [21, 32]])

In [99]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [100]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [101]:
b-a

array([[4, 4],
       [4, 4]])

In [102]:
a@b

array([[19, 22],
       [43, 50]])

In [103]:
a.T

array([[1, 3],
       [2, 4]])

In [104]:
a

array([[1, 2],
       [3, 4]])

In [105]:
#stacking 

In [106]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [107]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [108]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Exersises

In [5]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
sumX = np.sum(s, axis=1)
sumY = np.sum(s,axis=0)

sumX & sumY == 45 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [11]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [12]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [14]:
np.mean(data[:,0])

18.4

In [16]:
print(data[:,1])

[85 92 76 65 90]


In [17]:
np.max(data[:,2])

95

In [18]:
a = data[:,1]>90

In [ ]:
data[a]

array([[19, 92, 88]])

In [20]:
data[:,1]+5

array([90, 97, 81, 70, 95])